services:
  webserver:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - test-task

  app:
    container_name: test-task-react-node
    build:
      context: .
      dockerfile: ./docker/node-22/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - test-task

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-task
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-test-task:/var/lib/mysql
    networks:
      - test-task
networks:
  test-task:
    driver: bridge

volumes:
  mysql-test-task:
    driver: local
